# Generated by Django 4.2.7 on 2023-12-11 22:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketaForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kot', models.CharField(max_length=100, verbose_name='Кличка воспитанника')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('city', models.CharField(max_length=100, verbose_name='В каком городе вы живёте?')),
                ('home', models.CharField(max_length=100, verbose_name='Квартира или загородный дом?')),
                ('message', models.TextField(verbose_name='Расскажите коротко о себе')),
                ('phone', models.CharField(max_length=100, verbose_name='Ваш номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Ваша почта')),
            ],
            options={
                'verbose_name': 'Анкета клиента',
                'verbose_name_plural': 'Анкеты клиентов',
                'db_table': 'Ankety',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 1, 16, 37, 373580), verbose_name='Опубликована')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'статья блога',
                'verbose_name_plural': 'статьи блога',
                'db_table': 'Posts',
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='KotBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klichka', models.CharField(max_length=100, verbose_name='Кличка')),
                ('kratko', models.TextField(verbose_name='Немного о пушистом')),
                ('opisanie', models.TextField(verbose_name='Полное сожержание')),
                ('foto1', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к фото 1')),
                ('foto2', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к фото 2')),
                ('foto3', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к фото 3')),
                ('foto4', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к фото 4')),
            ],
            options={
                'verbose_name': 'Профиль воспитанника',
                'verbose_name_plural': 'Профили воспитанников',
                'db_table': 'Kotiki',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 1, 16, 37, 374576), verbose_name='Дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog', verbose_name='Статья комментария')),
            ],
            options={
                'verbose_name': 'Комментарии к статье блога',
                'verbose_name_plural': 'Комментарии к статьям блога',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
